adb/frontend/collection/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('adb.frontend.collection.views',
    url(r'^$', 'browse', name='browse'),
    url(r'^(?P<model>(movies|genres|actors))/(?P<letter>([a-z]|09|@!))/$', 'browse', name='browse_per_letter'),
    url(r'^movie/(\d+)/$', 'movie', name='movie'),
    url(r'^genre/(\d+)/$', 'genre', name='genre'),
    url(r'^actor/(\d+)/$', 'actor', name='actor'),
)

adb/frontend/lists/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('adb.frontend.lists.views',
    url(r'^$', 'index', name='index'),
    url(r'^create/$', 'edit', name='create'),
    url(r'^(?P<id>\d+)/$', 'view', name='view'),
    url(r'^(?P<id>\d+)/delete/$', 'delete', name='delete'),
    url(r'^(?P<id>\d+)/rename/$', 'edit', name='rename'),
)

adb/frontend/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^collection/', include('adb.frontend.collection.urls', namespace='collection')),
    url(r'^lists/', include('adb.frontend.lists.urls', namespace='lists')),
    
    url(r'^checker/', include('adb.frontend.checker.urls', namespace='checker')),
    
    url(r'^search/', include('haystack.urls')),
    
    url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}, name='index'),
    url(r'^login.html$', 'django.contrib.auth.views.login', {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout.html$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

adb/frontend/lists/models.py
from django.db import models
from django.contrib.auth.models import User

class List(models.Model):
    """
    A custom list tied to a given user.
    """
    
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    movies = models.ManyToManyField('collection.Movie', blank=True)
    
    class Meta:
        unique_together = (
            ('name', 'user'),
        )
        
        ordering = ('name', 'user')
        
        permissions = (
            ("browse_lists", "Can browse lists"),
            ("view_list", "Can view list contents"),
        )
    
    @models.permalink
    def get_absolute_url(self):
        return ('lists:view', (), {'id': str(self.id)})
        
    
    def __str__(self):
        return self.name.encode('utf-8')
    
    def __unicode__(self):
        return self.name

adb/frontend/lists/forms.py
from django import forms
from adb.frontend.lists.models import List


class ListForm(forms.ModelForm):
    name = forms.CharField(error_messages={
        'required': 'Inserisci un nome per la nuova lista da creare'
    })
    
    class Meta:
        model = List
        fields = ('name',)

adb/frontend/lists/views.py
# -*- coding: utf-8 -*-

from django.db import IntegrityError
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404

from adb.frontend.auth.decorators import permission_required, checks_permissions, require_permissions
from adb.frontend.lists.forms import ListForm
from adb.frontend.lists.models import List
from adb.frontend.shortcuts import render_to_response


@permission_required('lists.browse_lists')
def index(request):
    return render_to_response('lists/index.html', {
        'lists': request.user.list_set.all(),
    }, request)


@permission_required('lists.view_list')
def view(request, id):
    l = get_object_or_404(List, pk=id, user=request.user)
    
    return render_to_response('lists/view.html', {
        'list': l,
        'items': l.movies.all(),
    }, request)


@permission_required('lists.delete_list')
def delete(request, id):
    l = get_object_or_404(List, pk=id, user=request.user)
    
    if request.method == 'POST':
        l.delete()
        messages.success(request, u"La lista “%s” é stata correttamete eliminata." % l.name)
        return redirect('index')
    
    return render_to_response('lists/confirm.html', {
        'list': l,
    }, request)


@checks_permissions
def edit(request, id=None):
    if id is not None:
        require_permissions(request.user, 'lists.change_list')
        instance = get_object_or_404(List, pk=id, user=request.user)
    else:
        require_permissions(request.user, 'lists.add_list')
        instance = List(user=request.user)
    
    if request.method == 'POST':
        form = ListForm(request.POST, instance=instance)
        
        if form.is_valid():
            try:
                l = form.save()
                
                if id is None:
                    msg = u"La lista “%s” é stata creata correttamete."
                else:
                    msg = u"La lista “%s” é stata rinominata correttamete."
                
                messages.success(request, msg % l.name)
                return redirect(l)
            except IntegrityError:
                form._errors = {
                    'name': form.error_class([u'Non è possibile usare lo stesso nome per più liste'])
                }
    else:
        form = ListForm(instance=instance)
    
    return render_to_response('lists/edit.html', {
        'form': form,
        'instance': instance,
        'editing': id is not None,
    }, request)

templates/navigation/browsing.html
			<li id="browse-menu-item">
				<a href="{% url 'collection:browse' %}">Sfoglia</a>
				<ul>
					<li>
						<strong>Film</strong>
						<ul>
							{%- for l in letters %}
							<li><a href="{% url 'collection:browse_per_letter' model='movies',letter=l.lower() %}">{{ l }}</a></li>
							{%- endfor %}
						</ul>
					</li>
					<li>
						<strong>Generi</strong>
						<ul>
							{%- for l in letters %}
							<li><a href="{% url 'collection:browse_per_letter' model='genres',letter=l.lower() %}">{{ l }}</a></li>
							{%- endfor %}
						</ul>
					</li>
					<li>
						<strong>Attori</strong>
						<ul>
							{%- for l in letters %}
							<li><a href="{% url 'collection:browse_per_letter' model='actors',letter=l.lower() %}">{{ l }}</a></li>
							{%- endfor %}
						</ul>
					</li>
				</ul>
			</li>

templates/navigation/lists.html
			<li id="">
				<a href="{% url 'lists:index' %}">Liste</a>
				<ul>
					{%- for l in request.user.list_set.all() %}
					<li><a href="{{ l|url }}">{{ l.name }}</a></li>
					{%- endfor %}
					<li><a href="{% url 'lists:create' %}"><em>✚ Crea una nuova lista</em></a></li>
				</ul>
			</li>

templates/navigation/tools.html
			<li id="">
				<a href="#">Strumenti</a>
				<ul>
					<li><a href="#">Release creator</a></li>
					<li><a href="{% url 'checker:index' %}">Release checker</a></li>
				</ul>
			</li>