adb/frontend/lists/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('adb.frontend.lists.views',
    url(r'^$', 'index', name='index'),
    url(r'^create/$', 'edit', name='create'),
    url(r'^(?P<id>\d+)/$', 'view', name='view'),
    url(r'^(?P<id>\d+)/delete/$', 'delete', name='delete'),
    url(r'^(?P<id>\d+)/rename/$', 'edit', name='rename'),
)

adb/frontend/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^collection/', include('adb.frontend.collection.urls', namespace='collection')),
    url(r'^lists/', include('adb.frontend.lists.urls', namespace='lists')),
    
    url(r'^checker/', include('adb.frontend.checker.urls', namespace='checker')),
    
    url(r'^search/', include('haystack.urls')),
    
    url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}, name='index'),
    url(r'^login.html$', 'django.contrib.auth.views.login', {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout.html$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
)

adb/frontend/lists/models.py
from django.db import models
from django.contrib.auth.models import User

class List(models.Model):
    """
    A custom list tied to a given user.
    """
    
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User)
    movies = models.ManyToManyField('collection.Movie', blank=True)
    
    class Meta:
        unique_together = (
            ('name', 'user'),
        )
        
        ordering = ('name', 'user')
        
        permissions = (
            ("browse_lists", "Can browse lists"),
            ("view_list", "Can view list contents"),
        )
    
    @models.permalink
    def get_absolute_url(self):
        return ('lists:view', (), {'id': str(self.id)})
        
    
    def __str__(self):
        return self.name.encode('utf-8')
    
    def __unicode__(self):
        return self.name

adb/frontend/lists/forms.py
from django import forms
from adb.frontend.lists.models import List


class ListForm(forms.ModelForm):
    name = forms.CharField(error_messages={
        'required': 'Inserisci un nome per la nuova lista da creare'
    })
    
    class Meta:
        model = List
        fields = ('name',)

adb/frontend/lists/views.py
# -*- coding: utf-8 -*-

from django.db import IntegrityError
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404

from adb.frontend.auth.decorators import permission_required, checks_permissions, require_permissions
from adb.frontend.lists.forms import ListForm
from adb.frontend.lists.models import List
from adb.frontend.shortcuts import render_to_response


@permission_required('lists.browse_lists')
def index(request):
    return render_to_response('lists/index.html', {
        'lists': request.user.list_set.all(),
    }, request)


@permission_required('lists.view_list')
def view(request, id):
    l = get_object_or_404(List, pk=id, user=request.user)
    
    return render_to_response('lists/view.html', {
        'list': l,
        'items': l.movies.all(),
    }, request)


@permission_required('lists.delete_list')
def delete(request, id):
    l = get_object_or_404(List, pk=id, user=request.user)
    
    if request.method == 'POST':
        l.delete()
        messages.success(request, u"La lista “%s” é stata correttamete eliminata." % l.name)
        return redirect('index')
    
    return render_to_response('lists/confirm.html', {
        'list': l,
    }, request)


@checks_permissions
def edit(request, id=None):
    if id is not None:
        require_permissions(request.user, 'lists.change_list')
        instance = get_object_or_404(List, pk=id, user=request.user)
    else:
        require_permissions(request.user, 'lists.add_list')
        instance = List(user=request.user)
    
    if request.method == 'POST':
        form = ListForm(request.POST, instance=instance)
        
        if form.is_valid():
            try:
                l = form.save()
                
                if id is None:
                    msg = u"La lista “%s” é stata creata correttamete."
                else:
                    msg = u"La lista “%s” é stata rinominata correttamete."
                
                messages.success(request, msg % l.name)
                return redirect(l)
            except IntegrityError:
                form._errors = {
                    'name': form.error_class([u'Non è possibile usare lo stesso nome per più liste'])
                }
    else:
        form = ListForm(instance=instance)
    
    return render_to_response('lists/edit.html', {
        'form': form,
        'instance': instance,
        'editing': id is not None,
    }, request)

adb/frontend/lists/templates/lists/base.html
{% extends "base.html" %}

adb/frontend/lists/templates/lists/confirm.html
{% extends "lists/base.html" %}

{% block title %}{{ super() }} · Elimina lista{% endblock title %}

{% block bodyid %}confirm{% endblock %}

{% block content %}
	<section>
		<h1>Conferma eliminazione “{{ list.name }}”</h1>
		
		<p>Sei sicuro di voler eliminare la lista "{{ list.name }}"?<br />Questa azione comporterà la rimozione di {{ list.movies.count() }} film dalla lista e non è reversibile.</p>
		
		<form action="" method="post" accept-charset="utf-8" class="yesno">
			{% csrf_token %}
			<a class="button" href="{{ list|url }}">No, annulla</a>
			<button type="submit" class="negative">Si, elimina</button>
		</form>
	</section>
{% endblock %}

adb/frontend/lists/templates/lists/edit.html
{% extends "lists/base.html" %}

{% block title %}{{ super() }} · {% if editing %}Rinomina lista{% else %}Crea nuova lista{% endif %}{% endblock title %}

{% block bodyid %}lists_create{% endblock %}

{% block content %}
	<section>
		{% if editing %}
		<h1>Rinomina lista</h1>
		
		<p>Utilizzando il campo di testo sottostante è possibile rinominare la lista “{{ instance.name }}”. Ricorda che non puoi usare lo stesso nome per più di una lista.</p>
		{% else %}
		<h1>Crea una nuova lista</h1>
			
		<p>Grazie alle liste é possibile organizzare i diversi film presenti nel database a proprio piacimento e secondo i più svariati criteri.<br />Per esempio puoi creare una lista di “Film già visti”, una di “Film da guardare” ed una di “Favoriti”.</p>
		{% endif %}
		
		<form action="" method="post" accept-charset="utf-8">
			{% csrf_token %}
			{{ form.name.errors|safe }}
			{{ form.non_field_errors()|safe }}
			<p>
				{{ form.name|safe }}
				<button type="submit" class="inline">{% if editing %}Rinomina{% else %}Crea{% endif %}</button>
			</p>
		</form>
	</section>
{% endblock %}

adb/frontend/lists/templates/lists/index.html
{% extends "lists/base.html" %}

{% block title %}{{ super() }} · Liste personalizzate{% endblock title %}

{% block bodyid %}lists_index{% endblock %}

{% block content %}
	<section>
		<h1>Liste personalizzate</h1>
		
		<table>
			{% for list in lists %}
			<tr>
				<th scope="row"><a href="{{ list|url }}">{{ list.name }}</a></th>
				<td class="highlight"><strong>{{ list.movies.count() }}</strong> film</td>
				<td>
					<a href="{% url 'lists:rename' id=list.id %}" class="button small">Rinomina</a>
					<a href="{% url 'lists:delete' id=list.id %}" class="button small">Elimina</a>
				</td>
			</tr>
			{% endfor %}
		</table>
		<p><a class="button small" href="{% url 'lists:create' %}">Crea una nuova lista</a></p>
	</section>
{% endblock %}

adb/frontend/lists/templates/lists/view.html
{% extends "lists/base.html" %}

{% block title %}{{ super() }} · {{ list.name }} (lista){% endblock title %}

{% block bodyid %}lists_view{% endblock %}

{% block content %}
	<section>
		<h1>{{ list.name }} <sup>lista</sup></h1>
		
		<div class="actions">
			<a href="{% url 'lists:rename' id=list.id %}" class="button small">Rinomina</a>
			<a href="{% url 'lists:delete' id=list.id %}" class="button small">Elimina</a>
		</div>
		
		<table>
			{% include "collection/browse/_movietable.html" %}
		</table>
	</section>
{% endblock %}